### ISSUE TITLE
eXTra-Client mit Java 7 überprüfen

### ISSUE THREAD

**Issue by GoogleCodeExporter** [extra-standard/extra-standard#107]
```
Wir sollen ausprobieren, ob eXTra-Client einwandfrei mit Java 7 funktionieren 
kann.
```

Original issue reported on code.google.com by `lofidewa...@gmail.com` on 14 May 2014 at 12:51

**Comment by LeonidPotap** [comment]
eXTra Klient ist mit der Version 2.3.0 auf Java 8 umgestellt
