### ISSUE TITLE
Client-Authentifizierung mittels Zertifikat

### ISSUE THREAD

**Issue by Bloodrayne1995** [extra-standard/extra-standard#116]
Hallo,

wir im Pfalzklinikum versuchen den Client für die Übertragung von LBR-Codes an den DRV-Bund zu realisieren.
Allerdings ist die Dokumentation des Clients lückenhaft, was zum Beispiel das Thema Zertifikat-Authentifzierung angeht.
Wir haben nun versucht, soviel aus dem Quellcode zu lesen wie es uns möglich war und haben eine Vermutung woran das hängen könnte.

Zunächst zu den Fakten:
- LBR-Code-Übertragung funktioniert mittels einer extra-Nachricht an einen extra-SPOC
- Die Authentifizierung des Clients wird über ein P12-Zertifikat realisiert

Unsere Vermutung ist die [Zeile 145 in der Klasse ExtraTransportHTTP](https://github.com/extra-standard/extra-standard/blob/master/java/components/extra-outputplugin-http/src/main/java/de/extra/client/plugins/outputplugin/transport/ExtraTransportHttp.java#L145) (NS: extra-outputplugin-http/src/main/java/de/extra/client/plugins/outputplugin/transport). Unserer Meinung nach wird "setupTruststore" nur notwendig, wenn man keinen Truststore hat.
Wir haben allerdings schon einen Truststore erstellt und das Zertifikat bereits darin importiert, also für uns völlig unnötig.
Selbst wenn wir die Parameter für setupTruststore setzen, kann der Client das Zertifikat nicht einlesen ([Zeile 440](https://github.com/extra-standard/extra-standard/blob/master/java/components/extra-outputplugin-http/src/main/java/de/extra/client/plugins/outputplugin/transport/ExtraTransportHttp.java#L440)), obwohl wir das Zertifikat ins DER-Format konvertiert und als BASE64-Codierung bereitstellen ([s. Java API](https://docs.oracle.com/javase/7/docs/api/java/security/cert/CertificateFactory.html#generateCertificate(java.io.InputStream)))

Die Frage, die wir uns stellen, wie genau wir das Zertifikat einspielen müssen, sodass der extra-client es versteht und damit Verbindungen aufbauen kann.
Zur Veranschaulichung haben wir hier unsere Phase-Konfigurations-Dateien und die letzten Log-Files angehängt. Natürlich wurden die sensiblen Daten versteckt bzw. der KeyStore wurde entfernt.

Können Sie uns da weiterhelfen? Gerne können wir auch telefonieren, schreiben Sie mir dazu einfach eine Nachricht, dann gebe ich unsere Telefonnummer.

Mit freundlichen Grüßen
Marcel Serr
Pfalzklinikum für Psychiatrie und Neurologie AdöR

Anhänge:
[log_ohne_sslCertificate.log.txt](https://github.com/extra-standard/extra-standard/files/1057161/log_ohne_sslCertificate.log.txt)
[log_mit_sslCertificate.log.txt](https://github.com/extra-standard/extra-standard/files/1057162/log_mit_sslCertificate.log.txt)
[phase1.zip](https://github.com/extra-standard/extra-standard/files/1057155/phase1.zip)

**Comment by Korittky** [comment]
Hallo Herr Serr,

versuchen Sie mal nur den Parameter ...privateKeyStoreLocation zu konfigurieren und **nicht** plugins.outputplugin.httpOutputPlugin.sslTruststoreLocation. Dann wird letzterer mit cacerts des JDK initialisiert.
https://stackoverflow.com/questions/17935619/what-is-difference-between-cacerts-and-keystore

Wenn man versucht, den Truststore aus einer .jks-Datei zu initialisieren, läuft man in folgendes Problem:
https://stackoverflow.com/questions/42298149/null-pointer-exception-on-x509certificate-getsubjectdn-when-reading-ssl-certi

Ich hoffe, ich konnte Ihr Problem in der kurzen Zeit verstehen und lösen.

Mit freundlichen Grüßen,
Joachim Korittky

**Comment by Bloodrayne1995** [comment]
Hallo Hr. Korittky,

ich habe das nun einmal ausprobiert und bekam eine Fehlermeldung, dass das angegebene Passwort falsch sei. Was auf den ersten Blick nicht war.

Mir ist danach aufgefallen, dass der client nun den System-Truststore benutzt (was nicht weiter schlimm ist) und da das Passwort natürlich anders ist, nur wusste ich nicht das Passwort für den System-Truststore.
Ich dachte mir auch noch, dass ich dann das LBR-Zertifikat in diesem Truststore importieren muss, und habe dies mit Google und dem Keytool-Programm hinbekommen und die Daten in der user.properties-Datei des Clients wie folgt angepasst:
#plugins.outputplugin.httpOutputPlugin.sslTruststoreLocation=C:/tmp/extra-scenario-sendfetch/conf/phase1/test.jks
plugins.outputplugin.httpOutputPlugin.sslTruststorePassword=_changeit_
plugins.outputplugin.httpOutputPlugin.certificateAuthentification=true
plugins.outputplugin.httpOutputPlugin.privateKeyPassword=_u3F1MCIBL8l_

Zumindenst hat er nun das Zertifikat wohl akzeptiert (zumindenst meckert er nicht) und ich bekomme nun eine Nullpointer-Exception, da der Client aus der Eigenschaft **plugins.outputplugin.httpOutputPlugin.sslCertificate** ein Zertifikat haben möchte ([Zeile 440: ExtraTransportHttp.java](https://github.com/extra-standard/extra-standard/blob/master/java/components/extra-outputplugin-http/src/main/java/de/extra/client/plugins/outputplugin/transport/ExtraTransportHttp.java#L440)). Dies ist aber meiner Meinung nach nicht notwendig, weil er nichts anderes macht als das Zertifikat zu importieren.
Im Anhang habe ich auch die entsprechende Log-Datei beigefügt.

Können Sie mir da noch einmal behilflich sein?

Mit freundlichen Grüßen,
Marcel Serr

Anhänge:
[log_nach_TrustStore_Einstellung.log.txt](https://github.com/extra-standard/extra-standard/files/1057893/log_nach_TrustStore_Einstellung.log.txt)

**Comment by talalong** [comment]
Hallo,
unsere Firma hat auch gerade Problem mit der Zertifikat-Authentifizierung. Da stellt eXtra-standard die [WSDL-Datei](http://www.extra-standard.de/verfahren-nutzen/registrierte-verfahren/leistungsklassen-fuer-die-berufliche-rehabilitation-lbr.html) zur Verfügung, welche wir in Java code mit dem `wsimport` tool generieren lassen können. Außerdem wird die Zertifikat-Authentifizierung gar nicht in der Dokumentation erwähnt.
Nun wissen wir nicht, ob diese Referenzimplementierung noch aktuell ist.
@Bloodrayne1995 kann ich mich mit Ihnen in Verbindung setzten? Falls ja, hätte ich Sie gern per Email kontaktieren, weil Github das private Messaging-Feature beseitigt hat. Vielen Dank.
Mit freundlichen Grüßen
Long Luong

**Comment by Bloodrayne1995** [comment]
Hallo Hr. Luong,

gerne können Sie mich per E-Mail in Verbindung setzen.
Schreiben Sie mir einfach an [marcel.serr@pfalzklinikum.de](mailto://marcel.serr@pfalzklinikum.de) an.

Mit freundlichen Grüßen
Marcel Serr

**Comment by Bloodrayne1995** [comment]
Hallo Hr. Korittky,

da von Ihnen scheinbar keine Antwort dies bezüglich kommt und wir keine Eigenentwicklung aus diversen Gründen betreiben können, schließe ich diese Meldung.
Gerne können Sie diese Meldung auch als einen Art TODO-Eintrag setzen, falls Sie dies noch dokumentieren wollen.

Mit freundlichen Grüßen
Marcel Serr
